language: node_js
node_js:
- node
install:
- npm install
script:
- chmod +x .travis/build.sh && ./.travis/build.sh
after_script: 
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_890e64e2caf3_key -iv $encrypted_890e64e2caf3_iv
  -in .travis/id_rsa.travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'Gyumeijie'
- git config --global user.email '18170879819@163.com'
after_success:
- chmod +x .travis/gh-pages.sh && ./.travis/gh-pages.sh
