language: node_js
node_js:
- node
install:
- npm install
script:
- git clone git@github.com:Gyumeijie/css.io.git
- cp -r snippets css.io/
- cd css.io
- npm install
- npm run build
- cd ..
- cp -r css.io/docs .
after_script: 
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_6aef18dec71c_key -iv $encrypted_6aef18dec71c_iv
  -in .travis/id_rsa.travis.enc -out ~/.ssh/id_rsa -d
# Configure file access permission
- chmod 600 ~/.ssh/id_rsa
# Configure ssh
- cp .travis/ssh_config ~/.ssh/config
# Congfigure git information
- git config --global user.name 'Gyumeijie'
- git config --global user.email '18170879819@163.com'

script:
- git clone git@github.com:Gyumeijie/css.io.git
- cp -r snippets css.io/ && cd css.io
- npm install && npm run build
- cp -r docs ../ && cd -
- pwd && git status -s && ls -l docs

# Travis faild to deploy to github pages, so push manually
after_success:
- git checkout --orphan gh-pages
- git rm --cached -r .
- git add docs
- git commit -m"update at `date +"%Y-%m-%d %H:%M`"
# Make sure to make the output quiet, or else the API token will leak!
- git push -f git@github.com:Gyumeijie/code_snippets.CSS.git gh-pages